"""M1 business logic. Routers call these functions; no SQL in routers."""

import uuid

from sqlalchemy import func, select
from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.asyncio import AsyncSession
from starlette.concurrency import run_in_threadpool

from app.core.errors import AppError
from app.modules.auth.models import User
from app.modules.auth.schemas import LoginIn, RegisterIn
from app.modules.auth.security import hash_password, verify_password

# Computed once at import. Lets an unknown username cost the same bcrypt time as a wrong password.
_DUMMY_HASH = hash_password("timing-equalizer-not-a-real-password")


# 409 "username_taken"
async def register(db: AsyncSession, data: RegisterIn) -> User:
    user = User(username=data.username, password_hash=await run_in_threadpool(hash_password, data.password))
    db.add(user)
    try:
        await db.commit()
    except IntegrityError:  # the UNIQUE INDEX on lower(username) decides, not a prior SELECT
        await db.rollback()
        raise AppError(409, "username_taken", "Tên đăng nhập đã có người dùng") from None
    await db.refresh(user)  # load id + created_at generated by the database
    return user


# 401 "invalid_credentials" (same error for unknown user and wrong password)
async def authenticate(db: AsyncSession, data: LoginIn) -> User:
    user = await _find_by_username(db, data.username)
    hashed = user.password_hash if user is not None else _DUMMY_HASH
    ok = await run_in_threadpool(verify_password, data.password, hashed)
    if user is None or not ok:
        raise AppError(401, "invalid_credentials", "Sai tên đăng nhập hoặc mật khẩu")
    return user


async def get_user(db: AsyncSession, user_id: uuid.UUID) -> User | None:
    return await db.get(User, user_id)


async def _find_by_username(db: AsyncSession, username: str) -> User | None:
    stmt = select(User).where(func.lower(User.username) == username.lower())
    return (await db.execute(stmt)).scalar_one_or_none()
