/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Check credentials and set the session cookie.
         */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Clear the session cookie.
         */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Called by the frontend on startup to tell guests from logged-in users (401 = guest).
         */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Create an account and log in immediately (sets the session cookie).
         */
        post: operations["register_api_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Room
         * @description Create a room right away (criteria come later). The creator becomes the host.
         */
        post: operations["create_room_api_groups_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get State
         * @description Polling endpoint. If since_version == room.version, returns changed=False with an empty body.
         */
        get: operations["get_state_api_groups__code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{code}/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Finalize
         * @description Host ends voting early: the most-liked place wins (decided_by="host").
         */
        post: operations["finalize_api_groups__code__finalize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{code}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Join Room
         * @description Join the lobby. 409 if the room already started, is full or the name is taken; 410 if expired.
         */
        post: operations["join_room_api_groups__code__join_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{code}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start
         * @description Host only: fetch candidates from the CandidateProvider, store them, move to voting.
         */
        post: operations["start_api_groups__code__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{code}/votes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Vote
         * @description Upsert a vote, then apply rules.decide; the room may be decided in the same transaction.
         */
        post: operations["vote_api_groups__code__votes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Match
         * @description One best place + up to 3 backups. With USE_STUB_MATCH=true it returns sample data.
         */
        post: operations["match_api_match_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/match/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject
         * @description 'Không hợp': rerank the remaining backups by the reason. (Task 7, not implemented yet.)
         */
        post: operations["reject_api_match_reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/match/{place_id}/why": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Why
         * @description 'Why this place?' written by Gemini. (Task 5, not implemented yet.)
         */
        get: operations["why_api_match__place_id__why_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Reviews
         * @description Visible reviews written on the website, newest first (guests allowed). `is_mine` marks the caller's own.
         *
         *     Internal reviews imported from the team's form are not listed; they only feed Match and Analysis.
         */
        get: operations["list_reviews_api_reviews_get"];
        put?: never;
        /**
         * Create Review
         * @description Write a review. 409 if the caller already reviewed this place (edit it instead); 429 if too fast.
         *
         *     A review that trips the text filter is saved with status `flagged`: only its author sees it.
         */
        post: operations["create_review_api_reviews_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/analysis/{place_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Analysis
         * @description Review Analysis: 4 aspect scores, most mentioned dishes, pros/cons, tags (guests allowed).
         */
        get: operations["analysis_api_reviews_analysis__place_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * My Review
         * @description The caller's own review of a place (any status). 404 = they have not reviewed it yet.
         */
        get: operations["my_review_api_reviews_mine_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/{review_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Review
         * @description Replace the editable fields of the caller's own review. Not rate limited.
         */
        put: operations["update_review_api_reviews__review_id__put"];
        post?: never;
        /**
         * Delete Review
         * @description Delete the caller's own review.
         */
        delete: operations["delete_review_api_reviews__review_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/{review_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Report Review
         * @description 'Báo cáo' button. One report per person per review; 3 different reporters flag it.
         */
        post: operations["report_review_api_reviews__review_id__report_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AspectScores
         * @description Average of 1..5 scores per aspect, rounded to 1 decimal; null when there is no review.
         */
        AspectScores: {
            /** Food */
            food: number | null;
            /** Price */
            price: number | null;
            /** Service */
            service: number | null;
            /** Space */
            space: number | null;
        };
        /**
         * AuthUser
         * @description All that other modules ever see of a user: no password hash, no ORM object.
         */
        AuthUser: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Username */
            username: string;
        };
        /** CandidateOut */
        CandidateOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Likes */
            likes: number;
            /** Match Score */
            match_score: number;
            /** My Vote */
            my_vote: boolean | null;
            /** Place Id */
            place_id: string;
            /** Rank */
            rank: number;
            /** Tags */
            tags: string[];
        };
        /** CreateRoomIn */
        CreateRoomIn: {
            /**
             * Display Name
             * @example Hà
             */
            display_name: string;
        };
        /** GeoPoint */
        GeoPoint: {
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JoinRoomIn */
        JoinRoomIn: {
            /**
             * Display Name
             * @example Hà
             */
            display_name: string;
        };
        /**
         * JoinedOut
         * @description Returned exactly once. The client stores the token (per room code) and sends it back in
         *     the `X-Participant-Token` header on every following request.
         */
        JoinedOut: {
            /** Code */
            code: string;
            /** Is Host */
            is_host: boolean;
            /**
             * Participant Id
             * Format: uuid
             */
            participant_id: string;
            /** Participant Token */
            participant_token: string;
        };
        /** LoginIn */
        LoginIn: {
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /**
         * MatchCriteria
         * @description Search criteria shared by AI Match, Group Session and Food Journey.
         */
        MatchCriteria: {
            /**
             * Categories
             * @description e.g. ['cafe', 'main_meal']
             */
            categories?: string[];
            /**
             * Mood
             * @example quán yên tĩnh để học bài
             */
            mood: string;
            origin?: components["schemas"]["GeoPoint"] | null;
            /**
             * Price Max
             * @description VND per person
             */
            price_max?: number | null;
            /**
             * Price Min
             * @description VND per person
             */
            price_min?: number | null;
            /**
             * Radius M
             * @default 2000
             */
            radius_m: number;
        };
        /** MatchResponse */
        MatchResponse: {
            /**
             * Backups
             * @description up to 3 fallback places, best first; used by the 'Không hợp' button
             */
            backups?: components["schemas"]["MatchResult"][];
            /** @description null when nothing matches the criteria */
            best: components["schemas"]["MatchResult"] | null;
        };
        /**
         * MatchResult
         * @description A candidate plus the short reasons behind its score.
         *
         *     Inherited from PlaceCandidate: place_id, match_score (0..1, show it as round(score * 100) %),
         *     tags (3-4 short tags), distance_m (straight-line metres, None when the request has no origin).
         */
        MatchResult: {
            /**
             * Avg Rating
             * @description mean of our own reviews (sheet + web), 1..5; null when the place has no review
             */
            avg_rating?: number | null;
            /** Distance M */
            distance_m?: number | null;
            /** Match Score */
            match_score: number;
            /** Place Id */
            place_id: string;
            /**
             * Price Per Person
             * @description estimated VND per person (median of the reviews); null if unknown
             */
            price_per_person?: number | null;
            /**
             * Reasons
             * @description up to 4 ready-to-show Vietnamese lines (mood, distance, price, rating); a line is omitted when its data is missing. distance_m is straight-line: show it with a '~' or 'khoảng'
             */
            reasons?: string[];
            /**
             * Review Count
             * @description number of visible reviews behind avg_rating
             * @default 0
             */
            review_count: number;
            /**
             * Tags
             * @description short system-generated tags
             */
            tags?: string[];
        };
        /** ParticipantOut */
        ParticipantOut: {
            /** Display Name */
            display_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Host */
            is_host: boolean;
            /** Votes Cast */
            votes_cast: number;
        };
        /** RegisterIn */
        RegisterIn: {
            /** Password */
            password: string;
            /**
             * Username
             * @example ha_nguyen
             */
            username: string;
        };
        /**
         * RejectIn
         * @description 'Không hợp': the client keeps the backup list, so the server stays stateless.
         */
        RejectIn: {
            criteria: components["schemas"]["MatchCriteria"];
            reason: components["schemas"]["RejectReason"];
            /** Rejected Place Id */
            rejected_place_id: string;
            /**
             * Remaining
             * @description place_ids of the backups still available (client-side list)
             */
            remaining: string[];
        };
        /**
         * RejectReason
         * @enum {string}
         */
        RejectReason: "too_far" | "too_expensive" | "too_crowded" | "wrong_vibe";
        /** ReportIn */
        ReportIn: {
            /** Note */
            note?: string | null;
            /**
             * Reason
             * @enum {string}
             */
            reason: "spam" | "offensive" | "wrong_place" | "other";
        };
        /** ReportOut */
        ReportOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Reason
             * @enum {string}
             */
            reason: "spam" | "offensive" | "wrong_place" | "other";
            /**
             * Review Id
             * Format: uuid
             */
            review_id: string;
        };
        /**
         * ReviewAnalysisOut
         * @description Summary of the visible reviews of one place, computed with plain code (no LLM).
         */
        ReviewAnalysisOut: {
            aspects: components["schemas"]["AspectScores"];
            /** Atmosphere */
            atmosphere: components["schemas"]["TermCount"][];
            /** Cons */
            cons: components["schemas"]["TermCount"][];
            /**
             * Crowd Level
             * @description most common answer, null when nobody said
             */
            crowd_level: string | null;
            /**
             * Dishes
             * @description most mentioned recommended dishes
             */
            dishes: components["schemas"]["TermCount"][];
            /**
             * Overall
             * @description mean of the four aspect averages, 1 decimal
             */
            overall: number | null;
            /** Place Id */
            place_id: string;
            /** Pros */
            pros: components["schemas"]["TermCount"][];
            /** Review Count */
            review_count: number;
            /**
             * Sheet Review Count
             * @description reviews imported from the team's form
             */
            sheet_review_count: number;
            /** Suitable For */
            suitable_for: components["schemas"]["TermCount"][];
            /**
             * Typical Price
             * @description median VND per person, null when nobody said
             */
            typical_price: number | null;
            /**
             * User Review Count
             * @description reviews written on the website
             */
            user_review_count: number;
        };
        /** ReviewIn */
        ReviewIn: {
            /**
             * Comment
             * @description free text; an empty string is stored as null
             */
            comment?: string | null;
            /** Place Id */
            place_id: string;
            /**
             * Price Per Person
             * @description optional: VND spent per person
             */
            price_per_person?: number | null;
            /**
             * Recommended Dishes
             * @description optional: dishes worth trying
             */
            recommended_dishes?: string[];
            /** Score Food */
            score_food: number;
            /** Score Price */
            score_price: number;
            /** Score Service */
            score_service: number;
            /** Score Space */
            score_space: number;
            /**
             * Suitable For
             * @description optional: 'date', 'học bài', 'đi nhóm'...
             */
            suitable_for?: string[];
        };
        /** ReviewListOut */
        ReviewListOut: {
            /** Items */
            items: components["schemas"]["ReviewOut"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /**
             * Total
             * @description number of visible reviews of the place (for paging)
             */
            total: number;
        };
        /** ReviewOut */
        ReviewOut: {
            /**
             * Author
             * @description username; null for reviews imported from the team's form
             */
            author: string | null;
            /** Comment */
            comment: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Is Mine
             * @description true when the caller wrote it: show the edit/delete buttons
             */
            is_mine: boolean;
            /** Place Id */
            place_id: string;
            /** Price Per Person */
            price_per_person: number | null;
            /** Recommended Dishes */
            recommended_dishes: string[];
            /** Score Food */
            score_food: number;
            /** Score Price */
            score_price: number;
            /** Score Service */
            score_service: number;
            /** Score Space */
            score_space: number;
            /**
             * Source
             * @enum {string}
             */
            source: "user" | "sheet";
            /**
             * Status
             * @description other people only ever see 'visible'; the author may also see 'flagged'
             * @enum {string}
             */
            status: "visible" | "flagged" | "hidden";
            /** Suitable For */
            suitable_for: string[];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ReviewUpdateIn
         * @description PUT replaces every editable field, so the form can send the whole object back.
         */
        ReviewUpdateIn: {
            /**
             * Comment
             * @description free text; an empty string is stored as null
             */
            comment?: string | null;
            /**
             * Price Per Person
             * @description optional: VND spent per person
             */
            price_per_person?: number | null;
            /**
             * Recommended Dishes
             * @description optional: dishes worth trying
             */
            recommended_dishes?: string[];
            /** Score Food */
            score_food: number;
            /** Score Price */
            score_price: number;
            /** Score Service */
            score_service: number;
            /** Score Space */
            score_space: number;
            /**
             * Suitable For
             * @description optional: 'date', 'học bài', 'đi nhóm'...
             */
            suitable_for?: string[];
        };
        /** RoomStateOut */
        RoomStateOut: {
            /**
             * Candidates
             * @default []
             */
            candidates: components["schemas"]["CandidateOut"][];
            /**
             * Changed
             * @default true
             */
            changed: boolean;
            /** Code */
            code: string;
            /** Decided By */
            decided_by?: string | null;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Majority Threshold */
            majority_threshold?: number | null;
            /**
             * Me
             * Format: uuid
             */
            me: string;
            /**
             * Participants
             * @default []
             */
            participants: components["schemas"]["ParticipantOut"][];
            /** Poll Interval Ms */
            poll_interval_ms: number;
            /**
             * Server Time
             * Format: date-time
             */
            server_time: string;
            /**
             * Status
             * @enum {string}
             */
            status: "lobby" | "voting" | "decided" | "expired";
            /** Version */
            version: number;
            /** Winner Place Id */
            winner_place_id?: string | null;
        };
        /** StartIn */
        StartIn: {
            criteria: components["schemas"]["MatchCriteria"];
        };
        /** TermCount */
        TermCount: {
            /**
             * Mentions
             * @description how many reviews mention it
             */
            mentions: number;
            /** Name */
            name: string;
        };
        /** UserOut */
        UserOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Username */
            username: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VoteIn */
        VoteIn: {
            /**
             * Candidate Id
             * Format: uuid
             */
            candidate_id: string;
            /** Liked */
            liked: boolean;
        };
        /**
         * WhyOut
         * @description 'Why this place?'. Separate endpoint because the LLM call is slow.
         */
        WhyOut: {
            /** Place Id */
            place_id: string;
            /** Why */
            why: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUser"];
                };
            };
        };
    };
    register_api_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_room_api_groups_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRoomIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JoinedOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_state_api_groups__code__get: {
        parameters: {
            query?: {
                since_version?: number | null;
            };
            header: {
                "X-Participant-Token": string;
            };
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomStateOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finalize_api_groups__code__finalize_post: {
        parameters: {
            query?: never;
            header: {
                "X-Participant-Token": string;
            };
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomStateOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    join_room_api_groups__code__join_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinRoomIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JoinedOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Gone */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_api_groups__code__start_post: {
        parameters: {
            query?: never;
            header: {
                "X-Participant-Token": string;
            };
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomStateOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    vote_api_groups__code__votes_post: {
        parameters: {
            query?: never;
            header: {
                "X-Participant-Token": string;
            };
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoteIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomStateOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    match_api_match_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchCriteria"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_api_match_reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    why_api_match__place_id__why_get: {
        parameters: {
            query: {
                mood: string;
            };
            header?: never;
            path: {
                place_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_reviews_api_reviews_get: {
        parameters: {
            query: {
                place_id: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewListOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_review_api_reviews_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    analysis_api_reviews_analysis__place_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                place_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewAnalysisOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_review_api_reviews_mine_get: {
        parameters: {
            query: {
                place_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_review_api_reviews__review_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewUpdateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_review_api_reviews__review_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_review_api_reviews__review_id__report_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
