"""m4 add reports table

Revision ID: 661e222a251d
Revises: 52d2b6f6f57c
Create Date: 2026-10-07 18:17:39.957079
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "661e222a251d"
down_revision: str | Sequence[str] | None = "52d2b6f6f57c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reports",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("review_id", sa.UUID(), nullable=False),
        sa.Column("reporter_id", sa.UUID(), nullable=False),
        sa.Column("reason", sa.String(length=20), nullable=False),
        sa.Column("note", sa.String(length=300), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "reason IN ('spam', 'offensive', 'wrong_place', 'other')", name=op.f("ck_reports_reason_valid")
        ),
        sa.ForeignKeyConstraint(
            ["reporter_id"], ["users.id"], name=op.f("fk_reports_reporter_id_users"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["review_id"], ["reviews.id"], name=op.f("fk_reports_review_id_reviews"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
        sa.UniqueConstraint("review_id", "reporter_id", name="uq_reports_review_reporter"),
    )
    op.create_index(op.f("ix_reports_review_id"), "reports", ["review_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reports_review_id"), table_name="reports")
    op.drop_table("reports")
    # ### end Alembic commands ###
