"""m4 add reviews table

Revision ID: c1e52d5bd660
Revises: 42b5f39349c5
Create Date: 2026-10-06 13:57:11.173251
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "c1e52d5bd660"
down_revision: str | Sequence[str] | None = "42b5f39349c5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reviews",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("place_id", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("source", sa.String(length=10), server_default="user", nullable=False),
        sa.Column("import_key", sa.String(length=80), nullable=True),
        sa.Column("score_food", sa.SmallInteger(), nullable=False),
        sa.Column("score_space", sa.SmallInteger(), nullable=False),
        sa.Column("score_price", sa.SmallInteger(), nullable=False),
        sa.Column("score_service", sa.SmallInteger(), nullable=False),
        sa.Column("categories", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column("suitable_for", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column("atmosphere", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column("facilities", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column("food_types", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column("pros", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column("cons", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column("recommended_dishes", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column("crowd_level", sa.String(length=100), nullable=True),
        sa.Column("price_per_person", sa.Integer(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=10), server_default="visible", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "source <> 'user' OR user_id IS NOT NULL", name=op.f("ck_reviews_user_review_has_user")
        ),
        sa.CheckConstraint("source IN ('user', 'sheet')", name=op.f("ck_reviews_source_valid")),
        sa.CheckConstraint(
            "status IN ('visible', 'flagged', 'hidden')", name=op.f("ck_reviews_status_valid")
        ),
        sa.CheckConstraint("score_food BETWEEN 1 AND 5", name=op.f("ck_reviews_score_food_range")),
        sa.CheckConstraint("score_price BETWEEN 1 AND 5", name=op.f("ck_reviews_score_price_range")),
        sa.CheckConstraint("score_service BETWEEN 1 AND 5", name=op.f("ck_reviews_score_service_range")),
        sa.CheckConstraint("score_space BETWEEN 1 AND 5", name=op.f("ck_reviews_score_space_range")),
        sa.ForeignKeyConstraint(
            ["place_id"], ["places.place_id"], name=op.f("fk_reviews_place_id_places"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_reviews_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reviews")),
        sa.UniqueConstraint("import_key", name="uq_reviews_import_key"),
        sa.UniqueConstraint("user_id", "place_id", name="uq_reviews_user_place"),
    )
    op.create_index(op.f("ix_reviews_place_id"), "reviews", ["place_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reviews_place_id"), table_name="reviews")
    op.drop_table("reviews")
    # ### end Alembic commands ###
