"""m1 users + m5 group session

Revision ID: 2521105ec06e
Revises: 0001
Create Date: 2026-09-28 15:13:41.580260
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "2521105ec06e"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("username", sa.String(length=30), nullable=False),
        sa.Column("password_hash", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index("uq_users_username_lower", "users", [sa.literal_column("lower(username)")], unique=True)
    op.create_table(
        "group_rooms",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("code", sa.String(length=6), nullable=False),
        sa.Column("status", sa.String(length=10), server_default="lobby", nullable=False),
        sa.Column("criteria", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("version", sa.Integer(), server_default="0", nullable=False),
        sa.Column("member_count_at_start", sa.SmallInteger(), nullable=True),
        sa.Column("winner_place_id", sa.String(length=300), nullable=True),
        sa.Column("decided_by", sa.String(length=12), nullable=True),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('lobby', 'voting', 'decided', 'expired')", name=op.f("ck_group_rooms_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_group_rooms_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_group_rooms")),
        sa.UniqueConstraint("code", name=op.f("uq_group_rooms_code")),
    )
    op.create_table(
        "group_candidates",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("room_id", sa.UUID(), nullable=False),
        sa.Column("place_id", sa.String(length=300), nullable=False),
        sa.Column("rank", sa.SmallInteger(), nullable=False),
        sa.Column("match_score", sa.Float(), nullable=False),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["group_rooms.id"],
            name=op.f("fk_group_candidates_room_id_group_rooms"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_group_candidates")),
        sa.UniqueConstraint("room_id", "place_id", name=op.f("uq_group_candidates_room_id")),
    )
    op.create_table(
        "group_participants",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("room_id", sa.UUID(), nullable=False),
        sa.Column("display_name", sa.String(length=30), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("is_host", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("joined_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["group_rooms.id"],
            name=op.f("fk_group_participants_room_id_group_rooms"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_group_participants_user_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_group_participants")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_group_participants_token_hash")),
    )
    op.create_index(
        "uq_group_participants_room_name",
        "group_participants",
        ["room_id", sa.literal_column("lower(display_name)")],
        unique=True,
    )
    op.create_table(
        "group_votes",
        sa.Column("participant_id", sa.UUID(), nullable=False),
        sa.Column("candidate_id", sa.UUID(), nullable=False),
        sa.Column("room_id", sa.UUID(), nullable=False),
        sa.Column("liked", sa.Boolean(), nullable=False),
        sa.Column("voted_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["group_candidates.id"],
            name=op.f("fk_group_votes_candidate_id_group_candidates"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["participant_id"],
            ["group_participants.id"],
            name=op.f("fk_group_votes_participant_id_group_participants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["group_rooms.id"],
            name=op.f("fk_group_votes_room_id_group_rooms"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("participant_id", "candidate_id", name=op.f("pk_group_votes")),
    )
    op.create_index(op.f("ix_group_votes_room_id"), "group_votes", ["room_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_group_votes_room_id"), table_name="group_votes")
    op.drop_table("group_votes")
    op.drop_index("uq_group_participants_room_name", table_name="group_participants")
    op.drop_table("group_participants")
    op.drop_table("group_candidates")
    op.drop_table("group_rooms")
    op.drop_index("uq_users_username_lower", table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
