"""m3 m4 add places and reviews

Revision ID: 42b5f39349c5
Revises: 2521105ec06e
Create Date: 2026-10-05 22:42:26.003844
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "42b5f39349c5"
down_revision: str | Sequence[str] | None = "2521105ec06e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "places",
        sa.Column("place_id", sa.String(length=255), nullable=False),
        sa.Column("place_code", sa.String(length=10), nullable=False),
        sa.Column("manual_name", sa.String(length=200), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("google_maps_url", sa.Text(), nullable=True),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lng", sa.Float(), nullable=False),
        sa.Column("price_per_person", sa.Integer(), nullable=True),
        sa.Column("tiktok_urls", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("place_id", name=op.f("pk_places")),
        sa.UniqueConstraint("place_code", name=op.f("uq_places_place_code")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("places")
    # ### end Alembic commands ###
