"""m3 add place_embeddings

Revision ID: 52d2b6f6f57c
Revises: c1e52d5bd660
Create Date: 2026-10-06 18:41:25.833233
"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op


revision: str = "52d2b6f6f57c"
down_revision: str | Sequence[str] | None = "c1e52d5bd660"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "place_embeddings",
        sa.Column("place_id", sa.String(length=255), nullable=False),
        sa.Column("source_text", sa.Text(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
        sa.Column("model_name", sa.String(length=100), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["place_id"],
            ["places.place_id"],
            name=op.f("fk_place_embeddings_place_id_places"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("place_id", name=op.f("pk_place_embeddings")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("place_embeddings")
    # ### end Alembic commands ###
